version: '3'

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:80" 
    env_file:
      ./backend/.env
    depends_on:
      - db
    command: sh -c 'sleep 5 && php artisan migrate:refresh --seed && php-fpm --daemonize && nginx -g "daemon off;" && php artisan queue:work'

  db:
    image: postgres:14.10
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"    
   