version: '3'

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000" 
    env_file:
      ./backend/.env
    depends_on:
      - db
    command: sh -c "sleep 10 && php /var/www/html/artisan migrate --seed && php artisan serve --host=0.0.0.0 --port=8000  && php artisan queue:work"

  db:
    image: postgres:14.10
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"    
   