version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"  
    networks:
      - my_network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000" 
    depends_on:
      - postgres
    networks:
      - my_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: chat_expobank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" 
      # - "5433:5432" 
      
      
    networks:
      - my_network

networks:
  my_network:
    driver: bridge